export const ADD_SCRAPED_DATA = 'ADD_SCRAPED_DATA';
export const ADD_USER_COLLECTION = 'ADD_USER_COLLECTION';
export const ADD_TRANSMOG_SET = 'ADD_TRANSMOG_SET';
export const LOAD_TRANSMOG_SETS = 'LOAD_TRANSMOG_SETS';
export const ADD_VISUAL_TO_SET = 'ADD_VISUAL_TO_SET';
export const UPDATE_VISUAL_ID_HASH = 'UPDATE_VISUAL_ID_HASH';
export const FETCH_NAME_FOR_ITEM = 'FETCH_NAME_FOR_ITEM';
