const constants = {
    CATEGORY: {
        0: 'Unobtainable',
        1: 'Head',
        2: 'Shoulder',
        3: 'Back',
        4: 'Chest',
        5: 'Shirt',
        6: 'Tabard',
        7: 'Wrist',
        8: 'Hands',
        9: 'Waist',
        10: 'Legs',
        11: 'Feet',
        12: 'Wands',
        13: 'One-Handed Axes',
        14: 'One-Handed Swords',
        15: 'One-Handed Maces',
        16: 'Daggers',
        17: 'Fist Weapons',
        18: 'Shields',
        19: 'Held In Off-hand',
        20: 'Two-Handed Axes',
        21: 'Two-Handed Swords',
        22: 'Two-Handed Maces',
        23: 'Staves',
        24: 'Polearms',
        25: 'Bows',
        26: 'Guns',
        27: 'Crossbows',
        28: 'Warglaives',
        29: 'Legion Artifacts'
    },
    INVENTORY_TYPE: {
        1: 'INVTYPE_NON_EQUIP',
        2: 'INVTYPE_HEAD',
        3: 'INVTYPE_NECK',
        4: 'INVTYPE_SHOULDER',
        5: 'INVTYPE_BODY',
        6: 'INVTYPE_CHEST',
        7: 'INVTYPE_WAIST',
        8: 'INVTYPE_LEGS',
        9: 'INVTYPE_FEET',
        10: 'INVTYPE_WRIST',
        11: 'INVTYPE_HAND',
        12: 'INVTYPE_FINGER',
        13: 'INVTYPE_TRINKET',
        14: 'INVTYPE_WEAPON',
        15: 'INVTYPE_SHIELD',
        16: 'INVTYPE_RANGED',
        17: 'INVTYPE_CLOAK',
        18: 'INVTYPE_2HWEAPON',
        19: 'INVTYPE_BAG',
        20: 'INVTYPE_TABARD',
        21: 'INVTYPE_ROBE',
        22: 'INVTYPE_WEAPONMAINHAND',
        23: 'INVTYPE_WEAPONOFFHAND',
        24: 'INVTYPE_HOLDABLE',
        25: 'INVTYPE_AMMO',
        26: 'INVTYPE_THROWN',
        27: 'INVTYPE_RANGEDRIGHT',
        28: 'INVTYPE_QUIVER',
        29: 'INVTYPE_RELIC'
    },
    MOD_ID: {
        0: '',
        1: 'Normal',
        2: 'Heroic',
        3: 'Mythic',
        4: 'Raid Finder/Elite (PvP)'
    },
    ITEM_QUALITY: {
        0: 'Poor',
        1: 'Common',
        2: 'Uncommon',
        3: 'Rare',
        4: 'Epic',
        5: 'Legendary',
        6: 'Artifact',
        7: 'Heirloom',
        8: 'WoW Token'
    },
    TRANSMOG_SOURCE: {
        1: 'Boss Drop',
        2: 'Quest',
        3: 'Vendor',
        4: 'World Drop',
        5: 'Achievement',
        6: 'Profession',
    },
    MOG_SLOTS: [
        'Head', 
        'Shoulder', 
        'Back', 
        'Chest', 
        'Wrist', 
        'Hands', 
        'Waist', 
        'Legs', 
        'Feet'
    ]
}

export default constants;